import { type Config } from "tailwindcss";

export default {
  content: ["./src/**/*.tsx"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "inverse-primary": "#50d8e5",
        "inverse-surface": "#2e3133",
        outline: "#6c797b",
        "on-tertiary-fixed-variant": "#444748",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "primary-container": "#12b5c1",
        "surface-bright": "#f9f9fc",
        "surface-dim": "#d9dadd",
        "outline-variant": "#bbc9ca",
        "on-surface-variant": "#3c494a",
        "tertiary-fixed-dim": "#c4c7c8",
        "tertiary-container": "#a1a4a5",
        secondary: "#5e5e5e",
        "on-secondary-container": "#646464",
        "surface-variant": "#e1e2e6",
        "surface-container-high": "#e7e8eb",
        "surface-tint": "#006970",
        "on-background": "#191c1e",
        tertiary: "#5c5f60",
        error: "#ba1a1a",
        "secondary-container": "#e3e2e2",
        "secondary-fixed": "#e3e2e2",
        "surface-container-low": "#f3f3f7",
        "on-error-container": "#93000a",
        "primary-fixed": "#80f4ff",
        "surface-container": "#edeef1",
        "on-tertiary-container": "#373a3b",
        "inverse-on-surface": "#f0f0f4",
        "on-secondary-fixed": "#1b1c1c",
        "on-primary-container": "#004146",
        "on-tertiary-fixed": "#191c1d",
        primary: "#006970",
        "tertiary-fixed": "#e1e3e4",
        background: "#f9f9fc",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-fixed-variant": "#464747",
        "surface-container-highest": "#e1e2e6",
        "on-primary-fixed-variant": "#004f55",
        surface: "#f9f9fc",
        "primary-fixed-dim": "#50d8e5",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#002022",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "32px",
        unit: "8px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "margin-mobile": "24px",
        "section-gap": "120px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["var(--font-hanken)", "sans-serif"],
        "body-md": ["var(--font-hanken)", "sans-serif"],
        "body-lg": ["var(--font-hanken)", "sans-serif"],
        "headline-lg": ["var(--font-anton)", "sans-serif"],
        "headline-md": ["var(--font-hanken)", "sans-serif"],
        "label-sm": ["var(--font-hanken)", "sans-serif"],
        "display-lg": ["var(--font-anton)", "sans-serif"],
        "display-lg-mobile": ["var(--font-anton)", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.1", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" },
        ],
        "display-lg": [
          "84px",
          { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "display-lg-mobile": ["48px", { lineHeight: "1.1", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
